name: tugas_besar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: 0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.0.6
  webview_flutter: ^4.2.2
  appwrite: ^11.0.1

  image: 4.1.3
  flutter:
    sdk: flutter
  image_picker:

dev_dependencies:
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/images/
  uses-material-design: true
